### ISSUE TITLE
build-macstadium-macos1014-2 finding wrong bootjdk

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1301]
**Platform:**
MacOS

jdk11 for openj9 build is finding a jdk8 bootjdk:
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-x64-openj9/565/consoleFull
```
configure: Found potential Boot JDK using configure arguments
configure: Potential Boot JDK found at /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home is incorrect JDK version (openjdk version "1.8.0_252"); ignoring
configure: (Your Boot JDK version must be one of: 10 11)
configure: error: The path given by --with-boot-jdk does not contain a valid Boot JDK
```

**Comment by karianna** [comment]
We should fix the infra and then Andrew can revert his workaround

**Comment by gdams** [comment]
@andrew-m-leonard should be fixed now. Try again?

**Comment by andrew-m-leonard** [comment]
@gdams still a problem: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-x64-openj9/569/console

**Comment by andrew-m-leonard** [comment]
note for >jdk11 this kicks in: https://github.com/AdoptOpenJDK/openjdk-build/blob/9a784eb0622e9156ea2a86ee99730fa95a938d42/build-farm/platform-specific-configurations/linux.sh#L87
not sure why we can't use that for 11?

**Comment by gdams** [comment]
fixed by installing the `adoptopendjk10` cask. Should be resolved now
