### ISSUE TITLE
libffi.so dependency on zlinux HotSpot builds builds

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#19]
The openjdk builds on zlinux require libffi.so.4.

At the moment it seems like not all machines have the `libffi` package installed. This should be added to the ansible playlists and all the machines (`build-marist-s390x-rhel-6` is the most recent one I've ran on)

There is another issue whereby on Ubuntu 16 and RHEL7 the only `libffi` in the default repositories is `libffi.so.6` so the builds don't work out of the box - SLES12 is ok - but that will be s separate issue to address I suspect.

```
$ jdk8u144-b01/bin/java -version
Error: dl failure on line 893
Error: failed /dev/shm/y/jdk8u144-b01/jre/lib/s390x/server/libjvm.so, because libffi.so.4: cannot open shared object file: No such file or directory
```

**Comment by sxa555** [comment]
Somewhere between the "release" `jdk8u144-b01` and the current nightly `jdk8u172-b03` this one appears to have been resolved. Closing this as it will disappear as an issue once another build is promoted

**Comment by fjeremic** [comment]
@sxa555 can we please reopen this issue? I'm still seeing this using the following build:

https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u192-b12/OpenJDK8U-jdk_s390x_linux_hotspot_8u192b12.tar.gz

I tried SLES 12 SP1, RHEL 6.10, and RHEL 7.5. The issue still persists on all nightly Java 8 builds of Hotspot from Adopt as far back in time as I can go. The Java 9 builds seem to work fine however.

```
> ll
drwxr-xr-x  9 fjeremic fjeremic       4096 Oct 31 16:56 jdk8u192-b12
-rwxr-xr-x  1 fjeremic fjeremic        854 Nov 30 10:55 Test.class
-rwxr-xr-x  1 fjeremic fjeremic        345 Nov 30 12:19 Test.java
-rw-rw----  1 fjeremic fjeremic   74183341 Nov 30 12:24 OpenJDK8U-jdk_s390x_linux_hotspot_8u192b12.tar.gz
drwxrwxr-x  7 fjeremic fjeremic       4096 Nov 30 12:32 .

> jdk8u192-b12/bin/java -version
Error: dl failure on line 893
Error: failed /sandbox1/fjeremic/temp/jdk8u192-b12/jre/lib/s390x/server/libjvm.so, because libffi.so.6: cannot open shared object file: No such file or directory
```

Can we please reopen this issue so we can resolve this?
